name: Newman Test Run

on:
  pull_request:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install Newman
        run: npm install -g newman

      - name: Install Html extra Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Newman Collection
        env:
          URL: ${{ secrets.URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          newman run "Test collection.postman_collection.json" \
            --env-var "URL=${{ env.URL }}" \
            --env-var "USERNAME=${{ env.USERNAME }}" \
            --env-var "PASSWORD=${{ env.PASSWORD }}" \
            -r htmlextra \
            --reporter-htmlextra-export reports/report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-reporter
          path: reports/report.html
